set -g pane-active-border-style fg=pink
set -g pane-border-lines double
set -g pane-border-indicators arrows
set -g pane-border-status top

# keep current directory when splitting
bind * new-pane -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# note to self:
# prefix, :source-file ~/.tmux.conf to reload config for existing session

set -g mouse on

set -s extended-keys on
set -s extended-keys-format csi-u
set -as terminal-features 'xterm*:extkeys'
